SELECT
    COUNT(*) AS FISH_COUNT
FROM
(
    SELECT
        F.FISH_TYPE,
        N.FISH_NAME
    FROM FISH_INFO F
    LEFT JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
) R
